name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main  # Runs the workflow on push to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
